# Generated by Django 3.0.3 on 2020-03-28 03:43

import Apps.usuarios.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=59)),
                ('duracion', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('fecha', models.DateField()),
                ('foto', models.ImageField(upload_to=Apps.usuarios.models.images_path)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('duracion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('autor', models.CharField(max_length=100)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Album')),
            ],
        ),
    ]
